language: cpp
compiler:
  - clang
  - gcc
script: "./.travis/build"
before_install: "./.travis/before_install"
after_success: "./.travis/after_success"
after_failure: "./.travis/after_failure"
notifications:
  email:
    - roboptim@googlegroups.com
branches:
  only:
    - master
    - debian
matrix:
  allow_failures:
    - compiler: clang
env:
  global:
    secure: "Slm+HqRT+Vy0SG7E9gEShuHvNz6XWRUmBhVBLVJEaYy/0Lo2qp4OjFEWDjiJwFIiXstW2Wclds4SuewAn3Tc4x7dsY+5uaMCX7S/HPzsBCjLXUwjKasUqEGaVTIYmtFJm57hOkz6K2SLUUV4intkMiwtCiq/R0xe92QTTKkHyfo="
